### ISSUE TITLE
Overwrite Question?

### ISSUE THREAD

**Issue by ab623** [magmax/python-inquirer#10]
I would like to use inquirer as a menu. So when I provide a list, and the user selects the answer, I would like inquirer to overwrite the existing question. Is this possible? This feature would be great!

**Comment by magmax** [comment]
What do you mean with "override the existing question"? Do you want to modify the `Question` object or  just override the answer?

If you want to modify the `Question` object, it is not possible, because that was not the propose of Inquirer.

If you want to modify the answer, then it will be. This is the normal way of working for Inquirer.

But maybe there are other tools for that kind of things, like tkinter or curses.

**Comment by magmax** [comment]
Despite Inquirer won't modify the `Question` object, you can do it:

```python
questions = [
    Question('whatever', choices=['one', 'two', 'three'], default='one')
]

question_map = dict((q.name, q) for q in questions)

while True:
    answers = inquirer.prompt(questions)
    for k, v in answers:
        question_map[k].default = v
```

That should work (maybe some minor problems)

**Comment by amishb** [comment]
Hi, I'm sorry I should have been more detailed, as i rushed my question. 

When inquirer prompts for an answer for a list the the ouput looks something like 

```python
~ > python run.py
[?] Question 1
 >  Item 1
    Item 2
    Item 3
```

If i select ```Item 1``` I would like to prompt a new question, but overwrite the text displayed on the screen, with the new question, such that it looks like this now. 

```python
~ > python run.py
[?] You selected Item 1, What now?
    Item 1.1
 >  Item 1.2
    Item 1.3
```

This way you can use inquirer like a menu, by rewriting the display. 

Is this explanation better?

**Comment by magmax** [comment]
Ah, yes. That is supported out of the box. The `choices` variable can be a function that receives all the previous answers as argument (as a hash). So, you can use:

```
questions = [
    inquirer.List('items', choices=['item 1', 'item 2', item 3']),
    inquirer.List('whatever', choices=lambda x: [x['items'] + '.1', x['items'] + '.2', x['items'] + '.3'],
]
inquierer.prompt(questions)
```

There is a request to manage a hash instead of a list or a method, so you will be able to use a label and a value, so it will be even easier to do what you want to do. Stay tunned :D

**Comment by amishb** [comment]
Thanks for this. But it was a simplistic scenario. 

Imagine the menu:

* About
* Add

* Appliction

**Comment by Zearin** [comment]
:+1:

**Comment by magmax** [comment]
That is possible, but not easy, and is out of the scope of python-inquirer, I'm afraid.

There are other frameworks to do that, like courses or tkinter.

**Comment by AuHau** [comment]
As @magmax mentioned, this is out of scope, hence I am closing this issue.
