### ISSUE TITLE
Feature request: Vim+Emacs(Mac) keyword shortcuts for selection

### ISSUE THREAD

**Issue by zitudu** [magmax/python-inquirer#102]
I was wondering if it's possible to move cursor up/down-ward just like in vim or terminal?

That is:

`j` or `Ctrl-N` -> ↓
`k` or `Ctrl-P` -> ↑
`h` or `Ctrl-B` -> ←
`l` or `Ctrl-F` -> →

**Comment by andreatulimiero** [comment]
I believe giving users the chance to specify a different key combination to scroll up and down would be a nice addition and should be fairly easy to implement.
However, for some notorious key combinations (e.g., Ctrl-J or Ctrl-N) a change is required to [python-readchar](https://github.com/magmax/python-readchar) too.
If I am not mistaken, they are not [here](https://github.com/magmax/python-readchar/blob/master/readchar/key.py).

**Comment by mattcoding4days** [comment]
Looks like someone was working on this, but they didn't follow through. I have the code that provides this functionality (for vim atleast). I may implement Emacs

**Comment by Cube707** [comment]
if you have the code ready, feel free to open a PR and I will review it.

But reading https://github.com/magmax/python-inquirer/issues/102#issuecomment-769016354 I agree that it would probably be best to make this configurable (with the current behavior as defautl), instead of adding a bounch to the default behavior, possibly creating overlaps in functionalaty (for example `j` is usefull for _yes_ if your aplication is in german, etc...)

**Comment by Cube707** [comment]
also closing this because of what was discussed here https://github.com/magmax/python-inquirer/pull/560#issuecomment-2168153534
