### ISSUE TITLE
Remove traceback on keyboard interrupt

### ISSUE THREAD

**Issue by grm34** [magmax/python-inquirer#112]
Is is possible to add an exception in prompt.py to remove traceback on keyboard interrupt (or a sys.exit(0))?
Or maybe it's better to remove keyboard interrupt exception? I already handle that in my script but when inquirer is in use,  it's prompt.py exception which is run.

Thanks

**Comment by rednap** [comment]
same question!

**Comment by Cube707** [comment]
Hey, so I don't really understand your question? This is already implemented?

for example, running this:

```python
import inquirer

ans = inquirer.prompt([inquirer.Confirm("a", message="Should I continue")])

print(ans)
```

and pressing `CTR+C` instead of ansering, results in `Cancelled by user` beeing printed.

And if you want to have the `KeyboardInterrupt` re-raised, you can pass `raise_keyboard_interrupt=True` to the `prompt()` call.

**Comment by grm34** [comment]
Wow, it's 15 months old, I don't use it anymore and if I remember well it was the opposite: that the keyboard interruptions were not managed by python-inquirer. Thanks anyway
