### ISSUE TITLE
how to use validate in inquirer.Text

### ISSUE THREAD

**Issue by tgxpuisb** [magmax/python-inquirer#17]
i meet a qusetion that:

```
page_name = inquirer.prompt([
    inquirer.Text('name', message = 'support xxx.html or /xx/xxx.html', 
    validate = lambda x: re.match(r'/?([\w-]+?/)*[\w-]+\.html$', x))
 ])
```
```
page_name = inquirer.prompt([
    inquirer.Text('name', message = 'test', validate = lambda x: True,)
    ])
```
but no matter what i input, it still return      xxx is not a valid name

**Comment by magmax** [comment]
I am not at home. Can you try 'www.html'?

Thank you!

--
perdona que sea escueto... Te estoy escribiendo desde el móvil

**Comment by magmax** [comment]
Hello!
The method associated to validate receives two arguments: the hash with previous answers and the current answer. This is so in order to allow you to compare anything, for example.

So just try:

```
page_name = inquirer.prompt([
    inquirer.Text('name', message = 'support xxx.html or /xx/xxx.html', 
    validate = lambda _, x: re.match(r'/?([\w-]+?/)*[\w-]+\.html$', x))
 ])

page_name = inquirer.prompt([
    inquirer.Text('name', message = 'test', validate = lambda _, x: True,)
    ])
```

If any exception is raised in the lambda method (remember it can be a full method too), then it thinks it was not validated.

Regards!

**Comment by tgxpuisb** [comment]
oh~~, it worked, thx
